---
apiVersion: v1
kind: Service
metadata:
  name: kong-admin-pgl
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: kong-admin-pgl
    port: 8001
    targetPort: 8001
    protocol: TCP
  - name: kong-proxy-pgl
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: kong-pgl

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kong-rc-pgl
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: kong-rc-pgl
        app: kong-pgl
    spec:
      containers:
      - name: kong-pgl
        image: kong:0.9
        env:
          - name: KONG_DATABASE
            value: postgres
          - name: KONG_PG_USER
            value: kong
          - name: KONG_PG_DATABASE
            value: kong
          - name: KONG_PG_PASSWORD
            value: kong
          - name: KONG_PG_HOST
            value: 192.168.3.36
        ports:
        - name: admin-pgl
          containerPort: 8001
          protocol: TCP
        - name: proxy-pgl
          containerPort: 8000
          protocol: TCP
        - name: proxy-ssl-pgl
          containerPort: 8443
          protocol: TCP
        - name: surf-tcp-pgl
          containerPort: 7946
          protocol: TCP
        - name: surf-udp-pgl
          containerPort: 7946
          protocol: UDP
